all: dining dining1  dining3

dining: dining.c
	gcc -O -std=c99 -pthread -o dining dining.c

dining1: dining1.c
	gcc -O -std=c99 -pthread -o dining1 dining1.c

dining3: dining3.c
	gcc -O -std=c99 -pthread -o dining3 dining3.c